In [ ]:
# Get datasets as CSV: https://tools.wprdc.org/downstream/<CKAN resource ID>

# Scrape all of the resource ids for requests

In [204]:
import requests
from bs4 import BeautifulSoup

In [205]:
page = requests.get("https://data.wprdc.org/dataset/city-of-pittsburgh-building-permit-summary")

In [206]:
soup = BeautifulSoup(page.content, 'html.parser')

In [211]:
soup;

In [207]:
#lst = soup.find_all('li')
#lst = soup.find_all(class_="resource-item")
lst = soup.find_all(class_="heading")

In [209]:
len(lst)

112

In [214]:
lst[109]

<a class="heading" href="/dataset/city-of-pittsburgh-building-permit-summary/resource/3e0b6171-5d59-4e53-99e3-982b0e22a9f1" title="PLI: Building Permit Summary: January 2012">
    PLI: Building Permit Summary: January 2012<span class="format-label" data-format="xls" property="dc:format">XLS</span>
</a>

In [215]:
lst[109].get('href')

'/dataset/city-of-pittsburgh-building-permit-summary/resource/3e0b6171-5d59-4e53-99e3-982b0e22a9f1'

In [216]:
lst[109].get('title')

'PLI: Building Permit Summary: January 2012'

In [43]:
links = []
titles = []

In [44]:
for i in range(0,110):
    links.append(lst[i].get('href'))
    titles.append(lst[i].get('title'))

In [48]:
# Send dataset "resource id" strings to a file
with open('links.txt', 'w') as f:
    for value in links:
        f.write(value +'\n')

In [49]:
# Send dataset year and month strings to a file
with open('titles.txt', 'w') as f:
    for value in titles:
        f.write(value +'\n')

# Testing components
### Goal is to call all APIs, consolidate column names, see what fails, and save the data

In [1]:
links = []
with open('links.txt', 'r') as f:
    for value in f:
        links.append(value.rstrip())

In [5]:
titles = []
with open('titles.txt', 'r') as f:
    for value in f:
        titles.append(value.rstrip())

In [79]:
links[0]

'/dataset/city-of-pittsburgh-building-permit-summary/resource/ec07358d-747b-4a70-b25c-b4ddbd1d02ad'

In [80]:
resid = links[0].split('/')[-1]

In [81]:
yr = titles[0].split()[-1]

In [7]:
yr

'2021'

In [82]:
mon = titles[0].split()[-2]

In [10]:
yr+' '+mon

'2021 January'

In [ ]:
ids = []

In [9]:
#url_lead = 'https://tools.wprdc.org/downstream/'

In [13]:
#url_lead + resid

'https://tools.wprdc.org/downstream/ec07358d-747b-4a70-b25c-b4ddbd1d02ad'

In [14]:
#import requests

In [16]:
#response = requests.get(url_lead + resid)

In [13]:
#response.text

In [12]:
#dat = response.text.split('\n')

In [11]:
#dat

In [43]:
#data=dat[:5]

In [46]:
#for i in range(0,len(data)):
 #   data[i] = data[i].split(',')

In [14]:
#dat[1]

In [15]:
#data

In [ ]:
# Changing tactics: API

In [16]:
import json
import requests

In [62]:
url = 'https://data.wprdc.org/api/3/action/datastore_search?resource_id=' + resid + '&limit=5'

In [18]:
url

'https://data.wprdc.org/api/3/action/datastore_search?resource_id=ec07358d-747b-4a70-b25c-b4ddbd1d02ad&limit=5'

In [19]:
headers = {'Content-Type': 'application/json'}

In [63]:
resp = requests.get(url, headers = headers)

In [21]:
data = json.loads(resp.content.decode('utf-8'))

In [22]:
data.keys()

dict_keys(['help', 'success', 'result'])

In [28]:
data['result']['fields']

[{'type': 'int', 'id': '_id'},
 {'type': 'text', 'id': 'PERMIT NUMBER'},
 {'type': 'timestamp', 'id': 'ISSUED DATE'},
 {'type': 'text', 'id': 'PARCEL NUMBER'},
 {'type': 'text', 'id': 'ADDRESS'},
 {'type': 'text', 'id': 'NEIGHBORHOOD'},
 {'type': 'text', 'id': 'WARD'},
 {'type': 'text', 'id': 'OWNER NAME'},
 {'type': 'text', 'id': 'CONTRACTOR NAME'},
 {'type': 'text', 'id': 'TYPE OF WORK DESCRIPTION'},
 {'type': 'text', 'id': 'TYPE OF STRUCTURE'},
 {'type': 'text', 'id': 'WORK DESCRIPTION'},
 {'type': 'text', 'id': 'TOTAL PROJECT VALUE'}]

In [41]:
Yr = []
Mon = [] 
Field = [] 
Type = [] 
Field_Count = []

In [42]:
counter = 0
for d in data['result']['fields']:
    Yr.append(yr)
    Mon.append(mon)
    Field.append(d['id'].lower())
    Type.append(d['type'])
    Field_Count.append(counter)
    counter += 1

In [43]:
Field_Count

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [44]:
import pandas as pd

In [45]:
pd.DataFrame(list(zip(Yr, Mon,Field,Type,Field_Count)),
              columns=['Yr', 'Mon','Field','Type','Field_count'])

      Yr      Mon                     Field       Type  Field_count
0   2021  January                       _id        int            0
1   2021  January             permit number       text            1
2   2021  January               issued date  timestamp            2
3   2021  January             parcel number       text            3
4   2021  January                   address       text            4
5   2021  January              neighborhood       text            5
6   2021  January                      ward       text            6
7   2021  January                owner name       text            7
8   2021  January           contractor name       text            8
9   2021  January  type of work description       text            9
10  2021  January         type of structure       text           10
11  2021  January          work description       text           11
12  2021  January       total project value       text           12

In [47]:
len(titles)

110

In [ ]:
import json
import requests
import pandas as pd

set headers
set url leader
set empty lists

for links in links
get the resource id
get the title year and month
build url
make request
json load data
capture Fields

set counter to 0
for field in fields
append to lists

lists to dataframe

In [1]:
import json
import requests
import pandas as pd

In [2]:
links = []
with open('links.txt', 'r') as f:
    for value in f:
        links.append(value.rstrip())
        
titles = []
with open('titles.txt', 'r') as f:
    for value in f:
        titles.append(value.rstrip())
        
url_lead = 'https://data.wprdc.org/api/3/action/datastore_search?resource_id='
url_cond = '&limit=5'
headers = {'Content-Type': 'application/json'}

Yr = []
Mon = [] 
Field = [] 
Type = [] 
Field_Count = []
failed = []
        
for i in range(0,len(links)):
    resid = links[i].split('/')[-1]
    yr = titles[i].split()[-1]
    mon = titles[i].split()[-2]
    
    url = url_lead + resid + url_cond
    resp = requests.get(url, headers = headers)
    
    if resp.status_code == 200:
        data = json.loads(resp.content.decode('utf-8'))

        #print(i)
        counter = 0
        for d in data['result']['fields']:
            Yr.append(yr)
            Mon.append(mon)
            Field.append(d['id'].lower())
            Type.append(d['type'])
            Field_Count.append(counter)
            counter += 1
        
    else:
        failed.append([mon+' '+yr,resid])

df = pd.DataFrame(list(zip(Yr, Mon,Field,Type,Field_Count)),
              columns=['Yr', 'Mon','Field','Type','Field_count'])

In [3]:
failed

[['March 2018', '490a62f5-dff3-4cc5-a25a-a5a5e8b1e2c7'],
 ['October 2017', '4af6c93c-0d8a-4028-bc6f-7643b55ac07e'],
 ['September 2017', 'a31ab325-52c6-420d-b773-350d39ede1e2'],
 ['August 2017', '9ea45609-e3b0-445a-8ace-0addb973fdf5'],
 ['July 2017', 'cef41f9c-c245-4761-bcb2-6189898d0952'],
 ['June 2017', '4a169a2c-6908-45bd-9fc0-610514a5f065'],
 ['May 2017', '59548183-9976-4bcb-9700-950d19c145be'],
 ['April 2017', '0cf68def-708c-42f4-b368-ac97c109d6db'],
 ['January 2017', 'ed394aea-f7a4-45d0-99c8-f03f326b45c7'],
 ['December 2016', 'db59a57b-db2b-4d57-b60d-aa845a17ade8'],
 ['September 2016', '1be88945-1158-402b-8a04-36820ef877b4'],
 ['August 2016', 'ce4484a6-1130-43d5-b3b1-33415d3934b7'],
 ['July 2016', '9d60a789-7d2e-40d7-92dd-559eb03913d6'],
 ['June 2016', '7c608979-397d-48ae-ae14-386995046808'],
 ['February 2016', 'a17b1362-34f5-4e73-a7b0-32b1aab38692'],
 ['November 2015', 'febf5ecb-c8fe-4466-a6b3-840838c0920a'],
 ['January 2013', 'ac55ff92-d238-4bab-af8e-3f3a4e94fdfa']]

In [5]:
pd.DataFrame(failed, columns = ['mon_yr', 'resource_id']).to_csv('failed_permit_APIs.csv', index=False)

In [6]:
df

       Yr       Mon          Field       Type  Field_count
0    2021   January            _id        int            0
1    2021   January  permit number       text            1
2    2021   January    issued date  timestamp            2
3    2021   January  parcel number       text            3
4    2021   January        address       text            4
..    ...       ...            ...        ...          ...
864  2012       May           cost    numeric            9
865  2012     April            _id        int            0
866  2012     March            _id        int            0
867  2012  February            _id        int            0
868  2012   January            _id        int            0

[869 rows x 5 columns]

In [7]:
df['Field'].unique()

array(['_id', 'permit number', 'issued date', 'parcel number', 'address',
       'neighborhood', 'ward', 'owner name', 'contractor name',
       'type of work description', 'type of structure',
       'work description', 'total project value',
       'formatted parcel number', 'type of work', 'contractor',
       'permitnumber', 'issuedate', 'formattedparcelnumber',
       'addressableobjeformattedaddres', 'snp_neighborhood', 'snp_ward',
       'ownername', 'allcontractorsname', 'typeofworkdescription',
       'typeofstructure', 'workdescription', 'totalprojectvalue',
       'tota lproject value', 'issue date', 'parcel', 'updated date',
       'owner', 'cost', 'permit no.', 'permit #'], dtype=object)

In [8]:
df.groupby(['Field','Yr']).size().unstack(1)

Yr,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Field,,,,,,,,,,
_id,12.0,11.0,12.0,11.0,7.0,4.0,11.0,12.0,12.0,1.0
address,2.0,11.0,12.0,11.0,7.0,4.0,11.0,11.0,7.0,1.0
addressableobjeformattedaddres,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
allcontractorsname,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
contractor,2.0,11.0,12.0,11.0,7.0,4.0,11.0,4.0,1.0,NaN
contractor name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,6.0,1.0
cost,2.0,11.0,12.0,11.0,7.0,4.0,11.0,4.0,NaN,NaN
formatted parcel number,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
formattedparcelnumber,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
issue date,2.0,11.0,12.0,7.0,NaN,NaN,NaN,5.0,1.0,NaN
issued date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0
issuedate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN
neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,6.0,1.0
owner,2.0,11.0,12.0,11.0,7.0,4.0,11.0,4.0,NaN,NaN
owner name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,7.0,1.0
ownername,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
parcel,2.0,11.0,12.0,11.0,7.0,4.0,11.0,11.0,1.0,NaN
parcel number,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0
permit #,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
permit no.,NaN,11.0,12.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN
permit number,NaN,NaN,NaN,4.0,7.0,4.0,11.0,11.0,6.0,1.0
permitnumber,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN
snp_neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,6.0,NaN
snp_ward,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
tota lproject value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
total project value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,6.0,1.0
totalprojectvalue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
type of structure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,7.0,1.0
type of work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,6.0,NaN
type of work description,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
typeofstructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
typeofworkdescription,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
updated date,NaN,NaN,NaN,NaN,NaN,NaN,8.0,4.0,NaN,NaN
ward,2.0,11.0,12.0,11.0,7.0,4.0,11.0,11.0,7.0,1.0
work description,2.0,11.0,12.0,11.0,7.0,4.0,11.0,11.0,7.0,1.0
workdescription,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN

In [9]:
df.groupby(['Yr','Mon']).max('Field_count').unstack(1)

     Field_count                                                           \
Mon        April August December February January  July  June March   May
Yr
2012         0.0    0.0      0.0      0.0     0.0   9.0   0.0   0.0   9.0
2013         9.0    9.0      9.0      9.0     NaN   9.0   9.0   9.0   9.0
2014         9.0    9.0      9.0      9.0     9.0   9.0   9.0   9.0   9.0
2015         9.0    8.0      8.0      9.0     9.0   9.0   9.0   9.0   9.0
2016         8.0    NaN      NaN      NaN     8.0   NaN   NaN   8.0   8.0
2017         NaN    NaN      8.0      8.0     NaN   NaN   NaN   8.0   NaN
2018         9.0    8.0      9.0      8.0     8.0   9.0   9.0   NaN   9.0
2019         9.0   12.0     12.0      9.0     9.0  10.0  10.0   0.0   9.0
2020        12.0   12.0     12.0     12.0    12.0  12.0  12.0  12.0  12.0
2021         NaN    NaN      NaN      NaN    12.0   NaN   NaN   NaN   NaN


Mon  November October September
Yr
2012      0.0     0.0       0.0
2013      9.0     9.0       9.0
2014      9.0     9.0       9.0
2015      NaN     8.0       8.0
2016      8.0     8.0       NaN
2017      8.0     NaN       NaN
2018      9.0     9.0       9.0
2019     12.0    12.0      12.0
2020     12.0    12.0      12.0
2021      NaN     NaN       NaN

In [ ]:
# Next idea: Get the API data I can with consolidated columns names and dtypes, pull and merge these
# Figure out best way to get ~10-15 items that do NOT have API capture.

In [13]:
resid = links[0].split('/')[-1]

In [15]:
url = 'https://data.wprdc.org/api/3/action/datastore_search?resource_id=' + resid + '&limit=5'

In [16]:
resp = requests.get(url, headers = headers)

In [17]:
j = resp.json()

In [19]:
j;

In [20]:
pd.DataFrame.from_dict(j)

,help,success,result
_links,https://data.wprdc.org/api/3/action/help_show?...,True,{'start': '/api/3/action/datastore_search?limi...
fields,https://data.wprdc.org/api/3/action/help_show?...,True,"[{'type': 'int', 'id': '_id'}, {'type': 'text'..."
include_total,https://data.wprdc.org/api/3/action/help_show?...,True,True
limit,https://data.wprdc.org/api/3/action/help_show?...,True,5
records,https://data.wprdc.org/api/3/action/help_show?...,True,[{'TYPE OF STRUCTURE': 'Residential - Single F...
records_format,https://data.wprdc.org/api/3/action/help_show?...,True,objects
resource_id,https://data.wprdc.org/api/3/action/help_show?...,True,ec07358d-747b-4a70-b25c-b4ddbd1d02ad
total,https://data.wprdc.org/api/3/action/help_show?...,True,693

In [21]:
data = json.loads(resp.content.decode('utf-8'))
data

{'help': 'https://data.wprdc.org/api/3/action/help_show?name=datastore_search',
 'success': True,
 'result': {'include_total': True,
  'resource_id': 'ec07358d-747b-4a70-b25c-b4ddbd1d02ad',
  'fields': [{'type': 'int', 'id': '_id'},
   {'type': 'text', 'id': 'PERMIT NUMBER'},
   {'type': 'timestamp', 'id': 'ISSUED DATE'},
   {'type': 'text', 'id': 'PARCEL NUMBER'},
   {'type': 'text', 'id': 'ADDRESS'},
   {'type': 'text', 'id': 'NEIGHBORHOOD'},
   {'type': 'text', 'id': 'WARD'},
   {'type': 'text', 'id': 'OWNER NAME'},
   {'type': 'text', 'id': 'CONTRACTOR NAME'},
   {'type': 'text', 'id': 'TYPE OF WORK DESCRIPTION'},
   {'type': 'text', 'id': 'TYPE OF STRUCTURE'},
   {'type': 'text', 'id': 'WORK DESCRIPTION'},
   {'type': 'text', 'id': 'TOTAL PROJECT VALUE'}],
  'records_format': 'objects',
  'records': [{'TYPE OF STRUCTURE': 'Residential - Single Family',
    'PARCEL NUMBER': '0049-P-00248-0000-00',
    'NEIGHBORHOOD': 'Lower Lawrenceville',
    'OWNER NAME': '1301GRANDVIEW I LLC',
    'ISSUED DATE': '2021-01-01T00:00:00',
    'WORK DESCRIPTION': 'INTERIOR ALTERATIONS, NEW EXTERIOR DOORS AND WINDOWS AT A 2 STORY + ATTIC SINGLE-FAMILY ATTACHED DWELLING',
    'PERMIT NUMBER': 'EP-2020-20992',
    'CONTRACTOR NAME': 'D & S ELECTRIC PGH LLC',
    'ADDRESS': '335 39TH ST, Pittsburgh, 15201-',
    'TYPE OF WORK DESCRIPTION': 'ADDITION / ALTERATION',
    'WARD': '6',
    '_id': 1,
    'TOTAL PROJECT VALUE': '3000.0'},
   {'TYPE OF STRUCTURE': 'Residential - Two-Family',
    'PARCEL NUMBER': '0026-E-00072-0000-00',
    'NEIGHBORHOOD': 'Polish Hill',
    'OWNER NAME': 'WYLIE HOLDINGS LP',
    'ISSUED DATE': '2021-01-04T00:00:00',
    'WORK DESCRIPTION': 'Replacement of existing two-story deck structure with new in-kind replacement. The existing roof above the upper deck to remain.',
    'PERMIT NUMBER': 'BP-2020-17699',
    'CONTRACTOR NAME': 'W KING PROPERTIES INC DBA W KING BUILDERS',
    'ADDRESS': '3208 DOBSON ST, Pittsburgh, 15219-',
    'TYPE OF WORK DESCRIPTION': 'ADDITION / ALTERATION',
    'WARD': '6',
    '_id': 2,
    'TOTAL PROJECT VALUE': '12000.0'},
   {'TYPE OF STRUCTURE': 'Residential - Single Family',
    'PARCEL NUMBER': '0059-J-00282-0000-00',
    'NEIGHBORHOOD': 'Carrick',
    'OWNER NAME': 'MARCELLA PAULA HILARY RHAE',
    'ISSUED DATE': '2021-01-04T00:00:00',
    'WORK DESCRIPTION': '10\'X12" DECK',
    'PERMIT NUMBER': 'BP-2020-17732',
    'CONTRACTOR NAME': 'Stone Leigh Construction and Remodeling',
    'ADDRESS': '313 E AGNEW AVE, Pittsburgh, 15210-',
    'TYPE OF WORK DESCRIPTION': 'ADDITION / ALTERATION',
    'WARD': '29',
    '_id': 3,
    'TOTAL PROJECT VALUE': '8565.0'},
   {'TYPE OF STRUCTURE': 'Residential - Single Family',
    'PARCEL NUMBER': '0085-K-00033-0000-00',
    'NEIGHBORHOOD': 'Squirrel Hill North',
    'OWNER NAME': 'JAIN GIRISH',
    'ISSUED DATE': '2021-01-04T00:00:00',
    'WORK DESCRIPTION': 'CONSTRUCT 2 STORY ADDITION WITH BASEMENT, 1ST FLR DECK (FRONT), TRELLIS (FRONT & REAR) AND TRELLIS ABOVE FRONT DOOR, EXTERIOR & INTERIOR RENOVATIONS',
    'PERMIT NUMBER': '19-B-01691',
    'CONTRACTOR NAME': 'SENKO CONSTRUCTION, INC',
    'ADDRESS': '1200 S NEGLEY AVE, Pittsburgh, 15217-',
    'TYPE OF WORK DESCRIPTION': 'ADDITION / ALTERATION',
    'WARD': '14',
    '_id': 4,
    'TOTAL PROJECT VALUE': '150000.0'},
   {'TYPE OF STRUCTURE': 'Residential - Single Family',
    'PARCEL NUMBER': '0085-K-00033-0000-00',
    'NEIGHBORHOOD': 'Squirrel Hill North',
    'OWNER NAME': 'JAIN GIRISH',
    'ISSUED DATE': '2021-01-04T00:00:00',
    'WORK DESCRIPTION': 'NEW PARTIALLY COVERED 1ST FLOOR DECK WITH JACUZZI AT REAR OF HOUSE',
    'PERMIT NUMBER': 'BP-2020-05162',
    'CONTRACTOR NAME': 'SENKO CONSTRUCTION, INC',
    'ADDRESS': '1200 S NEGLEY AVE, Pittsburgh, 15217-',
    'TYPE OF WORK DESCRIPTION': 'ADDITION / ALTERATION',
    'WARD': '14',
    '_id': 5,
    'TOTAL PROJECT VALUE': '1.0'}],
  'limit': 5,
  '_links': {'start': '/api/3/action/datastore_search?limit=5&resource_id=ec07358d-747b-4a70-b25c-b4ddbd1d02ad',
   'next': '/api/3/action/datastore_search?offset=5&limit=5&resource_id=ec07358d-747b-4a70-b25c-b4ddbd1d02ad'},
  'total': 693}}

In [22]:
pd.json_normalize(data, ['result', 'fields'])

         type                        id
0         int                       _id
1        text             PERMIT NUMBER
2   timestamp               ISSUED DATE
3        text             PARCEL NUMBER
4        text                   ADDRESS
5        text              NEIGHBORHOOD
6        text                      WARD
7        text                OWNER NAME
8        text           CONTRACTOR NAME
9        text  TYPE OF WORK DESCRIPTION
10       text         TYPE OF STRUCTURE
11       text          WORK DESCRIPTION
12       text       TOTAL PROJECT VALUE

In [24]:
df = pd.json_normalize(data, ['result', 'records'])

In [26]:
df.head(3)

,TYPE OF STRUCTURE,PARCEL NUMBER,NEIGHBORHOOD,OWNER NAME,ISSUED DATE,WORK DESCRIPTION,PERMIT NUMBER,CONTRACTOR NAME,ADDRESS,TYPE OF WORK DESCRIPTION,WARD,_id,TOTAL PROJECT VALUE
0,Residential - Single Family,0049-P-00248-0000-00,Lower Lawrenceville,1301GRANDVIEW I LLC,2021-01-01T00:00:00,"INTERIOR ALTERATIONS, NEW EXTERIOR DOORS AND W...",EP-2020-20992,D & S ELECTRIC PGH LLC,"335 39TH ST, Pittsburgh, 15201-",ADDITION / ALTERATION,6,1,3000.0
1,Residential - Two-Family,0026-E-00072-0000-00,Polish Hill,WYLIE HOLDINGS LP,2021-01-04T00:00:00,Replacement of existing two-story deck structu...,BP-2020-17699,W KING PROPERTIES INC DBA W KING BUILDERS,"3208 DOBSON ST, Pittsburgh, 15219-",ADDITION / ALTERATION,6,2,12000.0
2,Residential - Single Family,0059-J-00282-0000-00,Carrick,MARCELLA PAULA HILARY RHAE,2021-01-04T00:00:00,"10'X12"" DECK",BP-2020-17732,Stone Leigh Construction and Remodeling,"313 E AGNEW AVE, Pittsburgh, 15210-",ADDITION / ALTERATION,29,3,8565.0

In [82]:
#if contains, then full replace this:
col_dict = {'address':'address',
    'contractor':'contractor',
    'value':'cost',
    'cost':'cost',
    'issue':'issue',
    'neigh':'neighborhood',
    'owner':'owner',
    'parcel':'parcel',
    'permit':'permit',
    'ward':'ward',
    'struct':'structure_type',
    'type of work':'work_type',
    'work description': 'workdescription',
    '_id':'id'
    }

In [83]:
df.columns

Index(['TYPE OF STRUCTURE', 'PARCEL NUMBER', 'NEIGHBORHOOD', 'OWNER NAME',
       'ISSUED DATE', 'WORK DESCRIPTION', 'PERMIT NUMBER', 'CONTRACTOR NAME',
       'ADDRESS', 'TYPE OF WORK DESCRIPTION', 'WARD', '_id',
       'TOTAL PROJECT VALUE'],
      dtype='object')

In [84]:
df.columns.str.lower()#.str.contains('address')

Index(['type of structure', 'parcel number', 'neighborhood', 'owner name',
       'issued date', 'work description', 'permit number', 'contractor name',
       'address', 'type of work description', 'ward', '_id',
       'total project value'],
      dtype='object')

In [85]:
conditions = '|'.join(list(col_dict.keys()))
conditions

'address|contractor|value|cost|issue|neigh|owner|parcel|permit|ward|struct|type of work|work description|_id'

In [86]:
regex_arr = df.columns.to_series().str.lower().str.contains(conditions, regex=True)
regex_arr

TYPE OF STRUCTURE           True
PARCEL NUMBER               True
NEIGHBORHOOD                True
OWNER NAME                  True
ISSUED DATE                 True
WORK DESCRIPTION            True
PERMIT NUMBER               True
CONTRACTOR NAME             True
ADDRESS                     True
TYPE OF WORK DESCRIPTION    True
WARD                        True
_id                         True
TOTAL PROJECT VALUE         True
dtype: bool

In [100]:
pd.Series([False,True]).any()

True

In [96]:
regex_arr.all()

True

In [87]:
regex_columns = df.columns.to_series().str.lower()[regex_arr]
regex_columns

TYPE OF STRUCTURE                  type of structure
PARCEL NUMBER                          parcel number
NEIGHBORHOOD                            neighborhood
OWNER NAME                                owner name
ISSUED DATE                              issued date
WORK DESCRIPTION                    work description
PERMIT NUMBER                          permit number
CONTRACTOR NAME                      contractor name
ADDRESS                                      address
TYPE OF WORK DESCRIPTION    type of work description
WARD                                            ward
_id                                              _id
TOTAL PROJECT VALUE              total project value
dtype: object

In [88]:
type(regex_columns)

pandas.core.series.Series

In [89]:
for v in regex_columns:
    for key in col_dict.keys():
        if key in v:
            regex_columns.replace(v,col_dict[key], inplace=True)

In [90]:
regex_columns

TYPE OF STRUCTURE            structure_type
PARCEL NUMBER                        parcel
NEIGHBORHOOD                   neighborhood
OWNER NAME                            owner
ISSUED DATE                           issue
WORK DESCRIPTION            workdescription
PERMIT NUMBER                        permit
CONTRACTOR NAME                  contractor
ADDRESS                             address
TYPE OF WORK DESCRIPTION          work_type
WARD                                   ward
_id                                      id
TOTAL PROJECT VALUE                    cost
dtype: object

In [91]:
df.columns = regex_columns

In [92]:
df

,structure_type,parcel,neighborhood,owner,issue,workdescription,permit,contractor,address,work_type,ward,id,cost
0,Residential - Single Family,0049-P-00248-0000-00,Lower Lawrenceville,1301GRANDVIEW I LLC,2021-01-01T00:00:00,"INTERIOR ALTERATIONS, NEW EXTERIOR DOORS AND W...",EP-2020-20992,D & S ELECTRIC PGH LLC,"335 39TH ST, Pittsburgh, 15201-",ADDITION / ALTERATION,6,1,3000.0
1,Residential - Two-Family,0026-E-00072-0000-00,Polish Hill,WYLIE HOLDINGS LP,2021-01-04T00:00:00,Replacement of existing two-story deck structu...,BP-2020-17699,W KING PROPERTIES INC DBA W KING BUILDERS,"3208 DOBSON ST, Pittsburgh, 15219-",ADDITION / ALTERATION,6,2,12000.0
2,Residential - Single Family,0059-J-00282-0000-00,Carrick,MARCELLA PAULA HILARY RHAE,2021-01-04T00:00:00,"10'X12"" DECK",BP-2020-17732,Stone Leigh Construction and Remodeling,"313 E AGNEW AVE, Pittsburgh, 15210-",ADDITION / ALTERATION,29,3,8565.0
3,Residential - Single Family,0085-K-00033-0000-00,Squirrel Hill North,JAIN GIRISH,2021-01-04T00:00:00,"CONSTRUCT 2 STORY ADDITION WITH BASEMENT, 1ST ...",19-B-01691,"SENKO CONSTRUCTION, INC","1200 S NEGLEY AVE, Pittsburgh, 15217-",ADDITION / ALTERATION,14,4,150000.0
4,Residential - Single Family,0085-K-00033-0000-00,Squirrel Hill North,JAIN GIRISH,2021-01-04T00:00:00,NEW PARTIALLY COVERED 1ST FLOOR DECK WITH JACU...,BP-2020-05162,"SENKO CONSTRUCTION, INC","1200 S NEGLEY AVE, Pittsburgh, 15217-",ADDITION / ALTERATION,14,5,1.0

In [ ]:
# handle certificate verification and SSL warnings
# https://urllib3.readthedocs.io/en/latest/user-guide.html#sslhttp = urllib3.PoolManager(
cert_reqs='CERT_REQUIRED',
ca_certs=certifi.where())
        
# get data from the API
url = 'https://maps2.dcgis.dc.gov/dcgis/rest/services/FEEDS/MPD/MapServer/2/query?where=1%3D1&outFields=*&outSR=4326&f=json'r = http.request('GET', url)
r.status

# decode json data into a dict object
data = json.loads(r.data.decode('utf-8'))
data

# in this dataset, the data to extract is under 'features' - FOR ME, it is under fields
df = pd.json_normalize(data, 'features')
df.head(10)

In [ ]:
## Test on a few full sets

In [93]:
df.dtypes

structure_type     object
parcel             object
neighborhood       object
owner              object
issue              object
workdescription    object
permit             object
contractor         object
address            object
work_type          object
ward               object
id                  int64
cost               object
dtype: object

In [94]:
test_sets = [links[0], links[15], links[68],links[86]]

In [ ]:
#if contains, then full replace this:
col_dict = {'address':'address',
    'contractor':'contractor',
    'value':'cost',
    'cost':'cost',
    'issue':'issue',
    'neigh':'neighborhood',
    'owner':'owner',
    'parcel':'parcel',
    'permit':'permit',
    'ward':'ward',
    'struct':'structure_type',
    'type of work':'work_type',
    'work description': 'workdescription',
    '_id':'id'
    }

In [101]:
df_list = []
#can change to a dictionary, just testing
conditions = '|'.join(list(col_dict.keys()))

In [102]:
for link in test_sets:

    resid = link.split('/')[-1]
    url = 'https://data.wprdc.org/api/3/action/datastore_search?resource_id=' + resid
    resp = requests.get(url, headers = headers)

    data = json.loads(resp.content.decode('utf-8'))
    #data

    df = pd.json_normalize(data, ['result', 'records'])

    regex_arr = df.columns.to_series().str.lower().str.contains(conditions, regex=True)

    if regex_arr.all():
        regex_columns = df.columns.to_series().str.lower()[regex_arr]
        for v in regex_columns:
            for key in col_dict.keys():
                if key in v:
                    regex_columns.replace(v,col_dict[key], inplace=True)
    
    df.columns = regex_columns
    df_list.append(df)

In [110]:
for i in df_list:
    print(sorted(i.columns))

['address', 'contractor', 'cost', 'id', 'issue', 'neighborhood', 'owner', 'parcel', 'permit', 'structure_type', 'ward', 'work_type', 'workdescription']
['address', 'contractor', 'cost', 'id', 'issue', 'neighborhood', 'owner', 'parcel', 'permit', 'structure_type', 'ward', 'work_type', 'workdescription']
['address', 'contractor', 'cost', 'id', 'issue', 'owner', 'parcel', 'permit', 'ward', 'workdescription']
['address', 'contractor', 'cost', 'id', 'issue', 'owner', 'parcel', 'permit', 'ward', 'workdescription']

In [ ]:
test_sets = [links[0], links[15], links[68],links[86]]

# Test - Cleaned process

In [2]:
import json
import requests
import pandas as pd
import numpy as np

In [15]:
links = []
with open('links.txt', 'r') as f:
    for value in f:
        links.append(value.rstrip())
        
titles = []
with open('titles.txt', 'r') as f:
    for value in f:
        titles.append(value.rstrip())

In [16]:
url_lead = 'https://data.wprdc.org/api/3/action/datastore_search?resource_id='
url_cond = '&limit=5'
headers = {'Content-Type': 'application/json'}

In [14]:
rnd = np.random.randint(0,high=100, size=5)
rnd

array([18, 94, 68, 15, 32])

In [17]:
test_links = [links[rnd[0]], links[rnd[1]], links[rnd[2]],links[rnd[3]],links[rnd[4]]]
test_titles = [titles[rnd[0]], titles[rnd[1]], titles[rnd[2]],titles[rnd[3]],titles[rnd[4]]]

In [30]:
#if contains, then full replace this:
col_dict = {'address':'address',
    'contractor':'contractor',
    'value':'cost',
    'cost':'cost',
    'date':'issued',
    'neigh':'neighborhood',
    'owner':'owner',
    'parcel':'parcel',
    'permit':'permit',
    'ward':'ward',
    'struct':'structure_type',
    'type of work':'work_type',
    'work description': 'workdescription',
    '_id':'id'
    }

conditions = '|'.join(list(col_dict.keys()))

In [38]:
failed_API = []
failed_rename = []
df_list = []

In [39]:
for i in range(0,len(test_links)):
    resid = test_links[i].split('/')[-1]
    yr = test_titles[i].split()[-1]
    mon = test_titles[i].split()[-2]

    url = url_lead + resid + url_cond
    r = requests.get(url, headers = headers)

    if r.status_code == 200:
        data = json.loads(r.content.decode('utf-8'))

        df = pd.json_normalize(data, ['result', 'records'])
        
        regex_arr = df.columns.to_series().str.lower().str.contains(conditions, regex=True)

        if regex_arr.all():
            regex_columns = df.columns.to_series().str.lower()[regex_arr]
            for v in regex_columns:
                for key in col_dict.keys():
                    if key in v:
                        regex_columns.replace(v,col_dict[key], inplace=True)

            df.columns = regex_columns
            df['year'] = yr
            df['month'] = mon
            df_list.append(df)
            
        else:
            failed_rename.append([mon+' '+yr,resid])

    else:
        failed_API.append([mon+' '+yr,resid])

In [45]:
df_list[0]

,structure_type,parcel,owner,permit,contractor,address,workdescription,ward,id,work_type,cost,year,month
0,Commercial - All other uses,0002-J-00104-0000-00,PITTSBURGH CBD LLC,19-B-01892,Sentinel Construction LLC,"301 GRANT ST, Pittsburgh, PA 15219",INTERIOR RENOVATIONS (740 SF) 37TH FLOOR AT A...,1,1,ADDITION / ALTERATION,110000,2019,July
1,Commercial - All other uses,0001-H-00030-0000-00,HRLP FOURTH AVENUE LLC,19-B-00074,A MARTINI & CO INC,"4 PPG PL, Pittsburgh, 15222-","REVISED - 15' X 42' 7"" ONE STORY MECHANICAL EN...",1,2,ADDITION / ALTERATION,530000,2019,July
2,Commercial - All other uses,0002-G-00009-0000-00,KSN INVESTMENTS LLC,19-B-00229,SADDLE CONSTRUCTION LLC,"1016 5TH AVE, Pittsburgh, 15219-","REPLACE FRONT FACADE, NEW OPENINGS FOR WINDOWS...",1,3,ADDITION / ALTERATION,200000,2019,July
3,Commercial - All other uses,0002-J-00260-0000-00,DIV 620 SECOND AVENUE LLC,18-B-04681,Shannon Construction Company,"615 1ST AVE, Pittsburgh, 15219-",INTERIOR AND EXTERIOR RENOVATIONS (AMENDING 19...,1,4,ADDITION / ALTERATION,2498000,2019,July
4,Commercial - All other uses,0001-H-00363-0000-00,BT PITT THIRD LLC,19-B-01123,Continental Building Company,"319 3RD AVE, Pittsburgh, 15222-","AMENDING 18-B-03690, INTERIOR AND EXTERIOR REN...",1,5,ADDITION / ALTERATION,3000000,2019,July

In [50]:
pd.concat(df_list, axis=0)

,structure_type,parcel,owner,permit,contractor,address,workdescription,ward,id,work_type,cost,year,month,issued,neighborhood
0,Commercial - All other uses,0002-J-00104-0000-00,PITTSBURGH CBD LLC,19-B-01892,Sentinel Construction LLC,"301 GRANT ST, Pittsburgh, PA 15219",INTERIOR RENOVATIONS (740 SF) 37TH FLOOR AT A...,1,1,ADDITION / ALTERATION,110000,2019,July,NaN,NaN
1,Commercial - All other uses,0001-H-00030-0000-00,HRLP FOURTH AVENUE LLC,19-B-00074,A MARTINI & CO INC,"4 PPG PL, Pittsburgh, 15222-","REVISED - 15' X 42' 7"" ONE STORY MECHANICAL EN...",1,2,ADDITION / ALTERATION,530000,2019,July,NaN,NaN
2,Commercial - All other uses,0002-G-00009-0000-00,KSN INVESTMENTS LLC,19-B-00229,SADDLE CONSTRUCTION LLC,"1016 5TH AVE, Pittsburgh, 15219-","REPLACE FRONT FACADE, NEW OPENINGS FOR WINDOWS...",1,3,ADDITION / ALTERATION,200000,2019,July,NaN,NaN
3,Commercial - All other uses,0002-J-00260-0000-00,DIV 620 SECOND AVENUE LLC,18-B-04681,Shannon Construction Company,"615 1ST AVE, Pittsburgh, 15219-",INTERIOR AND EXTERIOR RENOVATIONS (AMENDING 19...,1,4,ADDITION / ALTERATION,2498000,2019,July,NaN,NaN
4,Commercial - All other uses,0001-H-00363-0000-00,BT PITT THIRD LLC,19-B-01123,Continental Building Company,"319 3RD AVE, Pittsburgh, 15222-","AMENDING 18-B-03690, INTERIOR AND EXTERIOR REN...",1,5,ADDITION / ALTERATION,3000000,2019,July,NaN,NaN
0,NaN,0049L00317000000,Spano Susan M,11-B-00847,AARDVARD ADAPTIVE MODIFICATIONS LLC,4108 PENN AVE,"USE OF 1,17O SQ FT ON THE FIRST FLOOR AS RESTA...",9,1,NaN,5400,2013,April,2013-04-25 00:00:00,NaN
1,NaN,0013C00307000000,Jlb Development Group Llc,12-B-00947,TRENDS CAPITAL LLC,2371 HOLT ST,THREE STORY SINGLE FAMILY ATTACHED DWELLING WI...,16,2,NaN,125000,2013,April,2013-04-12 00:00:00,NaN
2,NaN,0002M00017000000,Forbes Stevenson Corporation,12-B-01302,BRIDGES & CO INC,1401 FORBES AVE,6504 SQ FT RENOVATION ON 2ND FLOOR,1,3,NaN,655000,2013,April,2013-04-24 00:00:00,NaN
3,NaN,0012M00204000000,Mccloskey John F & Jean (W),12-B-01554,"J. Francis Company, LLC",2526 LARKINS WAY,INTERIOR RENOVATION TO BATH AND KITCHEN IN 2 S...,16,4,NaN,12000,2013,April,2013-04-09 00:00:00,NaN
4,NaN,0013C00307000000,Jlb Development Group Llc,12-B-00948,TRENDS CAPITAL LLC,2375 HOLT,THREE STORY SINGLE FAMILY ATTACHED DWELLING WI...,16,5,NaN,125000,2013,April,2013-04-12 00:00:00,NaN
0,NaN,0046J00322000000,Oakglade Realty Capital Partners Lp,14-B-00690,OAKGLADE CAPITAL PARTNERS LLC,2246 WILSON AVE,INTERIOR AND EXTERIOR RENOVATIONS TO 3 STORY S...,26,1,NaN,80000,2015,July,2015-07-29T00:00:00,NaN
1,NaN,0028G00076 00,Rhodes Dan E,14-B-01569,Dan Rhodes,310 MEYRAN AVE,21' X 75' THREE-STORY ADDITION TO EXISTING TH...,4,2,NaN,225000,2015,July,2015-07-06T00:00:00,NaN
2,NaN,0028L00354000000,414 Mckee Place Lp,14-B-01463,,519 ZULEMA ST,NEW THREE STORY MULTIPLE FAMILY DWELLING STRUC...,4,3,NaN,1000000,2015,July,2015-07-21T00:00:00,NaN
3,NaN,0006J00021000000,Bradley Street Llp,14-B-02320,POMO DEVELOPMENT INC,438 BRADLEY ST,NEW CONSTRUCTION 2 STORY SINGLE FAMILY DWELLIN...,19,4,NaN,150000,2015,July,2015-07-09T00:00:00,NaN
4,NaN,0006J00023000000,Bradley Street Llp,14-B-02359,POMO DEVELOPMENT INC,432 BRADLEY ST,NEW CONSTRUCTION 2 STORY SINGLE FAMILY DWELLIN...,19,5,NaN,150000,2015,July,2015-07-09T00:00:00,NaN
0,Residential - Single Family,0087-M-00092-0000-00,FINEGOLD DAVID N & JUDITH H ESMAN (W),BP-2019-07153,RENEWAL BY ANDERSEN CORP,"2774 BEECHWOOD BLVD, Pittsburgh, 15217-",null,14,1,MINOR ALTERATION,18522,2019,October,2019-10-07T00:00:00,Squirrel Hill South
1,Residential - Single Family,0081-M-00350-0000-00,JAMES WILLIE C JR,BP-2019-07142,RENEWAL BY ANDERSEN CORP,"5114 ROSECREST PL, Pittsburgh, 15201-",null,10,2,MINOR ALTERATION,11978,2019,October,2019-10-07T00:00:00,Stanton Heights
2,Residential - Single Family,0087-F-00164-0000-00,SHI LINGYUN,BP-2019-07631,Home Depot USA,"2241 WIGHTMAN ST, Pittsburgh, 15217-",null,null,3,MINOR ALTERATION,1260,2019,October,2019-10-10T00:00:00,null
3,Residential - Single Family,0049-P-00023-0000-00,PREDIS ERIN R,BP-2019-08775,"RDN Pro Service and Development, LLC","3929 WOOLSLAYER Way, Pittsburgh, 15224-",null,null,4,MINOR ALTERATION,9000,2019,October,2019-10-28T00:00:00,null
4,Commercial - All other uses,0001-C-00228-0000-00,TOWN PLACE CONDOMINIUM ASSOCIATION,16-B-00648,KOSSMAN DEVELOPMENT COMPANY,"424 STANWIX ST, Pittsburgh, PA 15222-",INTERIOR RENOVATIONS AND NEW 13TH FLOOR ADDITI...,1,5,ADDITION / ALTERATION,1000,2019,October,2019-10-02T00:00:00,Central Business District
0,NaN,0001D00080000000,LIBERTY AVE HOLDINGS L L C,18-S-00100,GRUNAU COMPANY INC,"625 LIBERTY AVE, PITTSBURGH, PA 15222",RELOCATE SPRINKLER HEADS\r\nRELATED TO 18-B-00123,2,1,NaN,17000,2018,May,2018-05-01T00:00:00,NaN
1,NaN,0082R00190000000,VITONE DYLAN & ELAINE G (W),18-B-01497,GUNTON CORPORATION,"1012 N EUCLID AVE, PITTSBURGH, PA 15206","REPLACEMENT WINDOWS FOR 2.5 STORY, TWO-FAMILY ...",11,2,NaN,2000,2018,May,2018-05-01T00:00:00,NaN
2,NaN,0087R00261000000,HEYL JANET & ERIC (H),18-B-01498,GUNTON CORPORATION,"2913 SHADY AVE, PITTSBURGH, PA 15217","REPLACEMENT WINDOWS ON TWO-STORY, SINGLE-FAMIL...",14,3,NaN,1560,2018,May,2018-05-01T00:00:00,NaN
3,NaN,0123N00021000000,EGENHOFER URSULA E,18-B-01089,ESSIG RENOVATION & DESIGN,"1107 DEVICTOR PL, PITTSBURGH, PA 15206",INTERIOR AND EXTERIOR RENOVATIONS TO INCLUDE R...,11,4,NaN,130000,2018,May,2018-05-01T00:00:00,NaN
4,NaN,0088K00017000000,DZURA GARY S,18-B-01500,GUNTON CORPORATION,"3323 BEECHWOOD BLVD, PITTSBURGH, PA 15217","REPLACEMENT WINDOWS FOR TWO-STORY, SINGLE-FAMI...",14,5,NaN,14200,2018,May,2018-05-01T00:00:00,NaN

# Run API call over all API resource ids

In [2]:
import json
import requests
import pandas as pd
import numpy as np

In [218]:
links = []
with open('links.txt', 'r') as f:
    for value in f:
        links.append(value.rstrip())
        
titles = []
with open('titles.txt', 'r') as f:
    for value in f:
        titles.append(value.rstrip())

In [219]:
# Build urls
url_lead = 'https://data.wprdc.org/api/3/action/datastore_search?resource_id='
url_cond = '&limit=5000'
headers = {'Content-Type': 'application/json'}

In [17]:
# Set a dict to rename columns to create unified names to join on
# if contains, then full replace this:
col_dict = {'address':'address',
    'contractor':'contractor',
    'value':'cost',
    'cost':'cost',
    'date':'issued',
    'neigh':'neighborhood',
    'owner':'owner',
    'parcel':'parcel',
    'permit':'permit',
    'ward':'ward',
    'struct':'structure_type',
    'type of work':'work_type',
    'typeofwork':'typeofwork_description',
    'work description':'work description',
    'workdescription':'workdescription',
    '_id':'id'
    }

conditions = '|'.join(list(col_dict.keys()))

In [230]:
# Set lists to capture possible API failures
failed_API = [] # If dataset does not have API data
no_records = [] # if API call works, but there are no records
failed_rename = [] # if the rename dictionary doesn't fully capture columns
df_list = [] # Successful API data

In [231]:
for i in range(0,len(links)):
    resid = links[i].split('/')[-1]
    yr = titles[i].split()[-1]
    mon = titles[i].split()[-2]

    url = url_lead + resid + url_cond
    
    r = requests.get(url, headers = headers)

    if r.status_code == 200:
        data = json.loads(r.content.decode('utf-8'))

        df = pd.json_normalize(data, ['result', 'records'])
        
        regex_arr = df.columns.to_series().str.lower().str.contains(conditions, regex=True)

        if regex_arr.all():
            regex_columns = df.columns.to_series().str.lower()[regex_arr]
            for v in regex_columns:
                for key in col_dict.keys():
                    if key in v:
                        regex_columns.replace(v,col_dict[key], inplace=True)

            df.columns = regex_columns
            df['year'] = yr
            df['month'] = mon
            if len(df)==0:
                no_records.append([mon+' '+yr,resid])
            else:
                df_list.append(df)
            
        else:
            failed_rename.append([mon+' '+yr,resid])

    else:
        failed_API.append([mon+' '+yr,resid])

In [234]:
failed_rename

[]

In [232]:
len(df_list)

81

In [47]:
all_data = pd.concat(df_list, axis=0)

In [48]:
# Store successful API call data in raw csv
all_data.to_csv('raw_permit_data.csv', index=False)

In [235]:
no_records

[['March 2019', '13e8c9d5-0eb9-442d-bd2d-7dc6293946cb'],
 ['December 2012', '3807f2e2-e223-4026-8c3e-8939bc94643b'],
 ['November 2012', 'bd395d0e-99ec-4328-8c11-c6f8b5de7a8e'],
 ['October 2012', 'aa13f63f-6f0b-4709-9ff9-5ea90f6e5298'],
 ['September 2012', '0ee24d3e-5e8f-4642-933f-11b8ef22db4e'],
 ['August 2012', '329cda6a-6909-4ef8-8a6d-c312233fe5dd'],
 ['July 2012', 'b357d0a1-17d5-4513-8917-6832c4fc710f'],
 ['June 2012', '4e76b642-117e-4858-a7fd-447aa47f3279'],
 ['April 2012', '929e395b-5670-43f9-a6ac-94eff73f6bde'],
 ['March 2012', '94ea642c-ca0c-44d5-85c0-38d5be20dcea'],
 ['February 2012', '822af14b-e790-4506-82c6-2712b0f29d39'],
 ['January 2012', '3e0b6171-5d59-4e53-99e3-982b0e22a9f1']]

In [236]:
# Will need to get failed data sets another way
pd.DataFrame(no_records, columns=['date','resource_id']).to_csv('no_records.csv',index=False)

In [225]:
failed_API

[['March 2018', '490a62f5-dff3-4cc5-a25a-a5a5e8b1e2c7'],
 ['October 2017', '4af6c93c-0d8a-4028-bc6f-7643b55ac07e'],
 ['September 2017', 'a31ab325-52c6-420d-b773-350d39ede1e2'],
 ['August 2017', '9ea45609-e3b0-445a-8ace-0addb973fdf5'],
 ['July 2017', 'cef41f9c-c245-4761-bcb2-6189898d0952'],
 ['June 2017', '4a169a2c-6908-45bd-9fc0-610514a5f065'],
 ['May 2017', '59548183-9976-4bcb-9700-950d19c145be'],
 ['April 2017', '0cf68def-708c-42f4-b368-ac97c109d6db'],
 ['January 2017', 'ed394aea-f7a4-45d0-99c8-f03f326b45c7'],
 ['December 2016', 'db59a57b-db2b-4d57-b60d-aa845a17ade8'],
 ['September 2016', '1be88945-1158-402b-8a04-36820ef877b4'],
 ['August 2016', 'ce4484a6-1130-43d5-b3b1-33415d3934b7'],
 ['July 2016', '9d60a789-7d2e-40d7-92dd-559eb03913d6'],
 ['June 2016', '7c608979-397d-48ae-ae14-386995046808'],
 ['February 2016', 'a17b1362-34f5-4e73-a7b0-32b1aab38692'],
 ['November 2015', 'febf5ecb-c8fe-4466-a6b3-840838c0920a'],
 ['January 2013', 'ac55ff92-d238-4bab-af8e-3f3a4e94fdfa']]

In [104]:
pd.DataFrame(failed_API, columns=['date','resource_id']).to_csv('failed_API.csv',index=False)

# Clean and Merge API data with failed API data

In [1]:
import pandas as pd
import numpy as np
import re
import os
import datetime

In [49]:
api = pd.read_csv('raw_permit_data.csv')
api.head(3)

C:\Users\danie\anaconda_3\lib\site-packages\IPython\core\interactiveshell.py:3155: DtypeWarning: Columns (0,2,9,15,16) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,structure_type,parcel,neighborhood,owner,issued,work description,permit,contractor,address,work_type,ward,id,cost,year,month,workdescription,typeofwork_description
0,Residential - Single Family,0049-P-00248-0000-00,Lower Lawrenceville,1301GRANDVIEW I LLC,2021-01-01T00:00:00,"INTERIOR ALTERATIONS, NEW EXTERIOR DOORS AND W...",EP-2020-20992,D & S ELECTRIC PGH LLC,"335 39TH ST, Pittsburgh, 15201-",ADDITION / ALTERATION,6,1.0,3000.0,2021,January,NaN,NaN
1,Residential - Two-Family,0026-E-00072-0000-00,Polish Hill,WYLIE HOLDINGS LP,2021-01-04T00:00:00,Replacement of existing two-story deck structu...,BP-2020-17699,W KING PROPERTIES INC DBA W KING BUILDERS,"3208 DOBSON ST, Pittsburgh, 15219-",ADDITION / ALTERATION,6,2.0,12000.0,2021,January,NaN,NaN
2,Residential - Single Family,0059-J-00282-0000-00,Carrick,MARCELLA PAULA HILARY RHAE,2021-01-04T00:00:00,"10'X12"" DECK",BP-2020-17732,Stone Leigh Construction and Remodeling,"313 E AGNEW AVE, Pittsburgh, 15210-",ADDITION / ALTERATION,29,3.0,8565.0,2021,January,NaN,NaN

## Clean up API-returned data

In [64]:
api.isna().sum()

structure_type            40740
parcel                     1812
neighborhood              42555
owner                      1026
issued                    21156
work description           9990
permit                     1432
contractor                10252
address                    1794
work_type                 43556
ward                       2658
id                            0
cost                       1916
year                          0
month                         0
workdescription           54316
typeofwork_description    53248
dtype: int64

In [51]:
api.isna().sum()/len(api)*100

structure_type            72.181570
parcel                     3.210432
neighborhood              75.397318
owner                      1.817827
issued                    37.483390
work description          17.699899
permit                     2.537163
contractor                18.164101
address                    3.178540
work_type                 77.170851
ward                       4.709342
id                         0.000000
cost                       3.394695
year                       0.000000
month                      0.000000
workdescription           96.235006
typeofwork_description    94.342765
dtype: float64

In [52]:
idx = []
for i in range(0,len(api['permit'])):
    try:
        pd.to_datetime(api['permit'][i])
        idx.append(i)
    except:
        pass

In [59]:
api[api.index.isin(idx)].isna().sum()/len(api[api.index.isin(idx)])

structure_type            1.000000
parcel                    1.000000
neighborhood              1.000000
owner                     0.568638
issued                    0.997768
work description          0.996094
permit                    0.799107
contractor                1.000000
address                   1.000000
work_type                 1.000000
ward                      0.999442
id                        0.000000
cost                      0.992746
year                      0.000000
month                     0.000000
workdescription           1.000000
typeofwork_description    1.000000
dtype: float64

In [60]:
api[api.address.isna()]

,structure_type,parcel,neighborhood,owner,issued,work description,permit,contractor,address,work_type,ward,id,cost,year,month,workdescription,typeofwork_description
16109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2019,May,NaN,NaN
23835,NaN,NaN,NaN,NaN,NaN,NaN,8/2/2018,NaN,NaN,NaN,NaN,54.0,NaN,2018,August,NaN,NaN
23881,NaN,NaN,NaN,NaN,NaN,NaN,8/3/2018,NaN,NaN,NaN,NaN,100.0,NaN,2018,August,NaN,NaN
23930,NaN,NaN,NaN,NaN,NaN,NaN,8/6/2018,NaN,NaN,NaN,NaN,148.0,NaN,2018,August,NaN,NaN
23973,NaN,NaN,NaN,NaN,NaN,NaN,8/7/2018,NaN,NaN,NaN,NaN,192.0,NaN,2018,August,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,721.0,NaN,2012,May,NaN,NaN
56437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,722.0,NaN,2012,May,NaN,NaN
56438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,723.0,NaN,2012,May,NaN,NaN
56439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,724.0,NaN,2012,May,NaN,NaN
56440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,725.0,NaN,2012,May,NaN,NaN

In [80]:
# Drop null address - these are typically lines in which we had two owners, for example, 
# and this created a second row for the samr permit
api = api[~api.address.isna()]

In [81]:
api.isna().sum()/len(api)*100

structure_type            71.268322
parcel                     0.036599
neighborhood              74.589639
owner                      0.012809
issued                    35.438359
work description          15.014548
permit                     0.000000
contractor                15.477519
address                    0.000000
work_type                 76.421396
ward                       1.586546
id                         0.000000
cost                       0.250700
year                       0.000000
month                      0.000000
workdescription           96.111406
typeofwork_description    94.157044
dtype: float64

In [82]:
# consolidate the various description columns and drop old ones
api['work description'] = api['work description'].combine_first(api['workdescription']).combine_first(api['typeofwork_description'])

In [83]:
api = api.iloc[:,0:-2]

In [84]:
api.isna().sum()/len(api)*100

structure_type      71.268322
parcel               0.036599
neighborhood        74.589639
owner                0.012809
issued              35.438359
work description     9.164273
permit               0.000000
contractor          15.477519
address              0.000000
work_type           76.421396
ward                 1.586546
id                   0.000000
cost                 0.250700
year                 0.000000
month                0.000000
dtype: float64

In [85]:
 api['structure_type'].dtype == 'O'

True

In [86]:
# all lower case text
for col in api.columns:
    if api[col].dtype == 'O':
        api[col] = api[col].str.lower()

In [87]:
api.head(20)

,structure_type,parcel,neighborhood,owner,issued,work description,permit,contractor,address,work_type,ward,id,cost,year,month
0,residential - single family,0049-p-00248-0000-00,lower lawrenceville,1301grandview i llc,2021-01-01t00:00:00,"interior alterations, new exterior doors and w...",ep-2020-20992,d & s electric pgh llc,"335 39th st, pittsburgh, 15201-",addition / alteration,6,1.0,3000.0,2021,january
1,residential - two-family,0026-e-00072-0000-00,polish hill,wylie holdings lp,2021-01-04t00:00:00,replacement of existing two-story deck structu...,bp-2020-17699,w king properties inc dba w king builders,"3208 dobson st, pittsburgh, 15219-",addition / alteration,6,2.0,12000.0,2021,january
2,residential - single family,0059-j-00282-0000-00,carrick,marcella paula hilary rhae,2021-01-04t00:00:00,"10'x12"" deck",bp-2020-17732,stone leigh construction and remodeling,"313 e agnew ave, pittsburgh, 15210-",addition / alteration,29,3.0,8565.0,2021,january
3,residential - single family,0085-k-00033-0000-00,squirrel hill north,jain girish,2021-01-04t00:00:00,"construct 2 story addition with basement, 1st ...",19-b-01691,"senko construction, inc","1200 s negley ave, pittsburgh, 15217-",addition / alteration,14,4.0,150000.0,2021,january
4,residential - single family,0085-k-00033-0000-00,squirrel hill north,jain girish,2021-01-04t00:00:00,new partially covered 1st floor deck with jacu...,bp-2020-05162,"senko construction, inc","1200 s negley ave, pittsburgh, 15217-",addition / alteration,14,5.0,1.0,2021,january
5,residential - single family,0083-f-00233-0000-00,east liberty,eldi real estate llc,2021-01-04t00:00:00,new 2 story single family dwelling with detach...,bp-2020-07874,akator construction llc,"509 n saint clair st, pittsburgh, 15206-",new construction,11,6.0,236525.0,2021,january
6,residential - single family,0123-n-00199-0000-00,highland park,nalitz christine,2021-01-04t00:00:00,kitchen / dining room renovation including new...,bp-2020-06745,dale hummel construction,"1211 winterton st, pittsburgh, 15206-",addition / alteration,11,7.0,64000.0,2021,january
7,residential - single family,0086-g-00041-0000-00,squirrel hill north,scheines richard,2021-01-04t00:00:00,solar pv array,ep-2020-20823,"energy independent solutions,llc","5820 ferree st, pittsburgh, 15217-",addition / alteration,14,8.0,18250.0,2021,january
8,commercial - all other uses,0009-d-00200-0000-00,strip district,produce terminal holdings llc,2021-01-04t00:00:00,NaN,oop-2020-19069,NaN,"1615 smallman st, pittsburgh, pa 15222-",temporary use,2,9.0,0.0,2021,january
9,NaN,0052-d-00320-0000-00,shadyside,rosenbloom carol,2021-01-04t00:00:00,install (1) one 10.25 sf illuminated business ...,sp-2020-11046,custom signs inc,"5505 walnut st, pittsburgh, 15232-",new,7,10.0,16000.0,2021,january
10,commercial - all other uses,0010-n-00218-0000-00,crawford-roberts,ach clear pathways,2021-01-04t00:00:00,modifications to and extension of existing fir...,fas-2020-16716,"hatzel & buehler, inc","510 heldman st, pittsburgh, 15219-",addition / alteration,3,11.0,12000.0,2021,january
11,commercial - all other uses,0007-l-00032-0000-00,chateau,holdings acquisition co lp,2021-01-04t00:00:00,rework existing ansul system nozzles to prote...,ssp-2020-17022,"abco fire protection, inc.","777 casino dr, pittsburgh, pa 15212-",addition / alteration,21,12.0,2900.0,2021,january
12,residential,0011-d-00058-0000-00,west oakland,morgan scarlet,2021-01-04t00:00:00,install new furnace ac & ductwork,mp-2020-20927,bill wiseman contracting,"2512 allequippa st, pittsburgh, 15213-",addition / alteration,4,13.0,7250.0,2021,january
13,commercial,0070-n-00120-0000-02,fairywood,carondelet l p,2021-01-04t00:00:00,interior mechanical equipment and fuel gas pip...,mp-2020-19425,"junction climate control, inc.","2260 roswell dr, pittsburgh, pa 15205-",addition / alteration,28,14.0,8700.0,2021,january
14,commercial,0002-e-00038-0000-00,central business district,fac 525 llc,2021-01-04t00:00:00,interior alterations to mechanical system for ...,mp-2020-16065,ruthrauff sauer llc,"525 william penn pl, pittsburgh, 15219-",addition / alteration,2,15.0,104000.0,2021,january
15,residential,0083-b-00375-0000-00,highland park,steel town properties m3 llc,2021-01-04t00:00:00,interior structural modifications ; new 2 stor...,mp-2020-20928,bill wiseman contracting,"816 portland st, pittsburgh, 15206-",addition / alteration,11,16.0,7600.0,2021,january
16,commercial,0051-r-00150-0000-00,shadyside,shadyside hospital,2021-01-04t00:00:00,h.v.a.c. alterations associated with a new sta...,mp-2020-15875,ruthrauff sauer llc,"5230 centre ave, pittsburgh, pa 15232-",addition / alteration,7,17.0,52000.0,2021,january
17,commercial,0051-r-00150-0000-00,shadyside,shadyside hospital,2021-01-04t00:00:00,h.v.a.c. alterations to level g associated wit...,mp-2020-16731,ruthrauff sauer llc,"5230 centre ave, pittsburgh, pa 15232-",addition / alteration,7,18.0,142000.0,2021,january
18,commercial - all other uses,0003-h-00174-0000-00,south side flats,snap hook llc,2021-01-05t00:00:00,interior renovations to 1st floor in 3 story s...,15-b-03230,the kitchen & bath store inc,"1214 bingham st, pittsburgh, 15203-",addition / alteration,17,19.0,60000.0,2021,january
19,residential - single family,0001-n-00087-0000-00,mount washington,hawk edward w jr & mary ann (w),2021-01-05t00:00:00,construction of a two story addition (20’-6” x...,bp-2020-17393,brnardic corp,"220 bigham st, pittsburgh, 15211-",addition / alteration,19,20.0,100000.0,2021,january

In [88]:
# add source
api['source'] = 'API'

In [96]:
f = lambda x: x.rstrip('-') if x[-1] == '-' else x

In [102]:
api.head(3)

,structure_type,parcel,neighborhood,owner,issued,work description,permit,contractor,address,work_type,ward,id,cost,year,month,source
0,residential - single family,0049-p-00248-0000-00,lower lawrenceville,1301grandview i llc,2021-01-01t00:00:00,"interior alterations, new exterior doors and w...",ep-2020-20992,d & s electric pgh llc,"335 39th st, pittsburgh, 15201",addition / alteration,6,1.0,3000.0,2021,january,API
1,residential - two-family,0026-e-00072-0000-00,polish hill,wylie holdings lp,2021-01-04t00:00:00,replacement of existing two-story deck structu...,bp-2020-17699,w king properties inc dba w king builders,"3208 dobson st, pittsburgh, 15219",addition / alteration,6,2.0,12000.0,2021,january,API
2,residential - single family,0059-j-00282-0000-00,carrick,marcella paula hilary rhae,2021-01-04t00:00:00,"10'x12"" deck",bp-2020-17732,stone leigh construction and remodeling,"313 e agnew ave, pittsburgh, 15210",addition / alteration,29,3.0,8565.0,2021,january,API

In [101]:
# Clip the '-' at the end of a lot of zip codes in addresses
api['address']=api['address'].apply(lambda x: f(x))

In [103]:
api.to_csv('clean_api_data.csv', index=False)

## Get data from API calls that held no records

In [237]:
no_records

[['March 2019', '13e8c9d5-0eb9-442d-bd2d-7dc6293946cb'],
 ['December 2012', '3807f2e2-e223-4026-8c3e-8939bc94643b'],
 ['November 2012', 'bd395d0e-99ec-4328-8c11-c6f8b5de7a8e'],
 ['October 2012', 'aa13f63f-6f0b-4709-9ff9-5ea90f6e5298'],
 ['September 2012', '0ee24d3e-5e8f-4642-933f-11b8ef22db4e'],
 ['August 2012', '329cda6a-6909-4ef8-8a6d-c312233fe5dd'],
 ['July 2012', 'b357d0a1-17d5-4513-8917-6832c4fc710f'],
 ['June 2012', '4e76b642-117e-4858-a7fd-447aa47f3279'],
 ['April 2012', '929e395b-5670-43f9-a6ac-94eff73f6bde'],
 ['March 2012', '94ea642c-ca0c-44d5-85c0-38d5be20dcea'],
 ['February 2012', '822af14b-e790-4506-82c6-2712b0f29d39'],
 ['January 2012', '3e0b6171-5d59-4e53-99e3-982b0e22a9f1']]

In [28]:
basepath = 'C:\\Users\\danie\\Documents\\Studies by subject\\Capstone\\Data\\Permit data\\Non_API_datasets\\2012\\'
f = []
# all files to list
with os.scandir(basepath) as entries:
    for entry in entries:
        if entry.is_file():
            f.append(entry)

In [148]:
header_idx = []

In [149]:
# Need to skip rows for these 2012 datasets, but must pinpoint the header row
# This will attach the index of the row containing the headers
for i in f:
    data = pd.read_excel(basepath+i.name)
    
    for j in range(0,len(pd.Index(data).to_list())):
        if 'Address' in pd.Index(data).to_list()[j]:
            header_idx.append(j)
            #print(i.name)

apr2012.xls
aug2012.xls
dec2012.xls
feb2012.xls
jan2012.xls
jul2012.xls
jun2012.xls
mar2012.xls
nov2012.xls
oct2012.xls
sep2012.xls

In [150]:
header_idx

[11, 11, 11, 11, 11, 10, 12, 11, 10, 11, 11]

In [16]:
# Just to transform the names to get year, month columns like the API data
mns = {'jan':'january', 'feb':'february','mar':'march', 'apr':'april',
       'may':'may', 'jun':'june','jul':'july', 'aug':'august',
       'sep':'september', 'oct':'october','nov':'november', 'dec':'december'}
mn_d = {'january':1, 'february':2,'march':3, 'april':4,
       'may':5, 'june':6,'july':7, 'august':5,
       'september':9, 'october':10,'november':11, 'december':12,}

In [173]:
df_lst = []
for i in range(0,len(f)):
    dat = pd.read_excel(basepath+f[i].name, skiprows=header_idx[i]+1)
    dat['year'] = 2012
    dat['month'] = mns[f[i].name[:3]]
    dat['mn']=dat['month'].apply(lambda x:mn_d[x])
    df_lst.append(dat)

In [174]:
df_lst[0].columns.to_series().str.lower()

Issue Date                issue date
Permit No.                permit no.
Ward                            ward
Parcel                        parcel
Address                      address
Owner                          owner
Contractor                contractor
Work Description    work description
Cost                            cost
year                            year
month                          month
mn                                mn
dtype: object

In [180]:
# unify column names in the same way, lower case, all same rename conventions
for df in df_lst:
    cols = df.columns.to_series().str.lower()
    for col in cols:
        for key in col_dict.keys():
            if key in col:
                cols.replace(col,col_dict[key], inplace=True)

    df.columns = cols

In [183]:
df_lst[5];

In [184]:
all_2012 = pd.concat(df_lst, axis=0)

In [185]:
all_2012.isna().sum()/len(all_2012)*100

issued              30.677541
permit              30.708908
ward                30.834379
parcel              30.771644
address             30.740276
owner               30.834379
contractor          31.273526
work description    35.664994
cost                30.457967
year                 0.000000
month                0.000000
mn                   0.000000
description         94.981179
dtype: float64

In [188]:
# July got weird... drop all of these empty columns
all_2012[all_2012.address.isna()][:20]

,issued,permit,ward,parcel,address,owner,contractor,work description,cost,year,month,mn,description
179,NaT,NaN,NaN,NaN,NaN,NaN,NaN,TOTAL:,18514045,2012,april,4,NaN
159,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28234650,2012,december,12,TOTAL
157,NaT,NaN,NaN,NaN,NaN,NaN,NaN,TOTAL:,25960458,2012,february,2,NaN
135,NaT,NaN,NaN,NaN,NaN,NaN,NaN,TOTAL:,8941809,2012,january,1,NaN
251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.2491e+07,2012,july,7,NaN
252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,july,7,NaN
253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,july,7,NaN
254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,july,7,NaN
255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,july,7,NaN
256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,july,7,NaN
257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,july,7,NaN
258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,july,7,NaN
259,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,july,7,NaN
260,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,july,7,NaN
261,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,july,7,NaN
262,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,july,7,NaN
263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,july,7,NaN
264,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,july,7,NaN
265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,july,7,NaN
266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,july,7,NaN

In [193]:
all2012 = all_2012[~all_2012.address.isna()]

In [195]:
all2012.isna().sum()/len(all2012)*100

issued               0.000000
permit               0.000000
ward                 0.135870
parcel               0.045290
address              0.000000
owner                0.135870
contractor           0.769928
work description     7.336957
cost                 0.000000
year                 0.000000
month                0.000000
mn                   0.000000
description         92.798913
dtype: float64

In [200]:
all2012 = all2012.iloc[:,:-1]

In [215]:
all2012.to_csv('combined2012.csv', index=False)

In [12]:
all12 = pd.read_csv('combined2012.csv')

In [13]:
for col in all12.columns:
    if all12[col].dtype == 'O':
        all12[col] = all12[col].str.lower()

In [15]:
all12.head(2)

,issued,permit,ward,parcel,address,owner,contractor,work description,cost,year,month,mn
0,2012-04-11 00:00:00,11-b-01592,1.0,0001m00034000000,4 smithfield st,jd & d enterprises,tri-state contracting & dev co,elevator pit to basement,55000.0,2012,april,4
1,2012-04-11 00:00:00,11-b-02417,1.0,0001h00187000a00,245 4th ave,j & r holding inc,americo construction,construction of a new roof and roof top deck (...,180000.0,2012,april,4

In [16]:
city = ', pittsburgh, pa'
all12['address'] = all12['address'].apply(lambda x: x+city)

In [17]:
all12.head(2)

,issued,permit,ward,parcel,address,owner,contractor,work description,cost,year,month,mn
0,2012-04-11 00:00:00,11-b-01592,1.0,0001m00034000000,"4 smithfield st, pittsburgh, pa",jd & d enterprises,tri-state contracting & dev co,elevator pit to basement,55000.0,2012,april,4
1,2012-04-11 00:00:00,11-b-02417,1.0,0001h00187000a00,"245 4th ave, pittsburgh, pa",j & r holding inc,americo construction,construction of a new roof and roof top deck (...,180000.0,2012,april,4

In [26]:
all12['source'] = 'xls'

In [27]:
all12.to_csv('combined2012.csv', index=False)

## Clean up combined non-API data

This data was terrible and needed brute force excel downloading and manipulation to make usable for import.
For example, there were city of Pittsburgh insignia picture in the file, there were line breaks including a date for the rows below it, but not including the date on the line.... This couldn't be wrangled because the data was stored as text... So, the combined file read in here was consolidated with downloads and aggregation.

In [3]:
excl = pd.read_csv('Non_API_datasets/combined.csv')
excl.head()

,permit,ward,parcel,address,owner,contractor,workdescription,cost,issued,year,month
0,16-E-01558,14.0,0128A00056000001,"2332 BEECHWOOD BLVD, PITTSBURGH, PA 15217",BOARD OF PUBLIC EDUCATION OF THE SCHOOL DISTRI...,ALLEGHENY CITY ELECTRIC,INSTALL (2) 20A OUTLETS,300.0,7/1/2016,2016,July
1,16-E-01743,4.0,0028P00178000000,"3202 NIAGARA SQ, PITTSBURGH, PA 15213",REDLINGER ANDREW & NICOLE (W),NaN,INSTALL ELECTRICAL,2400.0,7/1/2016,2016,July
2,16-B-02182,17.0,0003L00170000000,"120 S 11TH ST, PITTSBURGH, PA 15203",CZEKAJ WALTER P & DANA M (W),NaN,"ON A 2-1/2 STORY SINGLE FAMILY DWELLING, INTER...",12000.0,7/1/2016,2016,July
3,16-M-00350,2.0,0002A00097000000,"535 SMITHFIELD ST, PITTSBURGH, PA 15222",MCKNIGHT 535 SMITHFIELD LP,A-AIR COMPANY,ADDING 1 - 15 TON AND 1 - 25 TON AIR HANDLING ...,58648.0,7/1/2016,2016,July
4,16-B-02181,10.0,0050L00330000000,"5159 PENN AVE, PITTSBURGH, PA 15224",ENGLAND RYAN M,NaN,INTERIOR RENOVATIONS ON A 3 STORY SINGLE FAMIL...,5000.0,7/1/2016,2016,July

In [4]:
len(excl)

17158

In [5]:
excl.rename(columns={'workdescription':'work description'}, inplace=True)

In [6]:
excl.isna().sum()/len(excl)*100

permit               0.000000
ward                 0.093251
parcel               0.169017
address              0.000000
owner                0.034969
contractor          24.624082
work description     1.626064
cost                 0.000000
issued               0.000000
year                 0.000000
month                0.000000
dtype: float64

In [7]:
for col in excl.columns:
    if excl[col].dtype == 'O':
        excl[col] = excl[col].str.lower()

In [8]:
excl.head()

,permit,ward,parcel,address,owner,contractor,work description,cost,issued,year,month
0,16-e-01558,14.0,0128a00056000001,"2332 beechwood blvd, pittsburgh, pa 15217",board of public education of the school distri...,allegheny city electric,install (2) 20a outlets,300.0,7/1/2016,2016,july
1,16-e-01743,4.0,0028p00178000000,"3202 niagara sq, pittsburgh, pa 15213",redlinger andrew & nicole (w),NaN,install electrical,2400.0,7/1/2016,2016,july
2,16-b-02182,17.0,0003l00170000000,"120 s 11th st, pittsburgh, pa 15203",czekaj walter p & dana m (w),NaN,"on a 2-1/2 story single family dwelling, inter...",12000.0,7/1/2016,2016,july
3,16-m-00350,2.0,0002a00097000000,"535 smithfield st, pittsburgh, pa 15222",mcknight 535 smithfield lp,a-air company,adding 1 - 15 ton and 1 - 25 ton air handling ...,58648.0,7/1/2016,2016,july
4,16-b-02181,10.0,0050l00330000000,"5159 penn ave, pittsburgh, pa 15224",england ryan m,NaN,interior renovations on a 3 story single famil...,5000.0,7/1/2016,2016,july

In [9]:
excl['source'] = 'xslx'

In [11]:
excl.to_csv('failed_api_data.csv', index=False)

## get the one outlier set that came from the .xls files from no-record APIs

In [13]:
df = pd.read_excel('Non_API_datasets/pli_buildingpermits_march2019.xls')

In [14]:
df.head()

,UPDATED DATE,Permit Number,Ward,PARCEL,Address,Owner,Contractor,Work Description,Cost
0,2019-03-01,18-B-03955,2.0,0009G00080000000,"1654 SMALLMAN ST, PITTSBURGH, PA 15222",KEICHER BROS ENTERPRISES,P.J. DICK INCORPORATED,INTERIOR AND EXTERIOR RENOVATION OF EXISTING S...,9739000.0
1,2019-03-01,18-B-03957,2.0,0009G00080000000,"1606 SMALLMAN ST, PITTSBURGH, PA 15222",KEICHER BROS ENTERPRISES,P.J. DICK INCORPORATED,NEW CONSTRUCTION OF ACCESSORY PARKING STRUCTUR...,3648000.0
2,2019-03-01,18-F-00398,4.0,0027M00104000000,"4400 5TH AVE, PITTSBURGH, PA 15213",MELLON INSTITUTE,NaN,FIRE ALARM ALTERATIONS RELATED 18-B-03763/18-B...,12000.0
3,2019-03-01,19-E-00152,12.0,0122L00050000000,"7779 LOCK WAY, PITTSBURGH, PA 15206",CITY OF PITTSBURGH,"FRANKL ELECTRIC, INC.","ELECTRICAL ALTERATIONS TO INCLUDE SUBPANEL, TR...",66300.0
4,2019-03-01,19-E-00151,12.0,0171B00001000002,"900 FREEPORT RD, PITTSBURGH, PA 15238",CITY OF PITTSBURGH,"FRANKL ELECTRIC, INC.",ELECTRICAL ALTERATIONS IN BASEMENT AND ON 1ST ...,100080.0

In [18]:
cols = df.columns.to_series().str.lower()
for col in cols:
    for key in col_dict.keys():
        if key in col:
            cols.replace(col,col_dict[key], inplace=True)

df.columns = cols

In [19]:
for col in df.columns:
    if df[col].dtype == 'O':
        df[col] = df[col].str.lower()

In [20]:
df['year'] = 2019
df['month'] = 'march'
df['mn'] = 3

In [21]:
df.head(2)

,issued,permit,ward,parcel,address,owner,contractor,work description,cost,year,month,mn
0,2019-03-01,18-b-03955,2.0,0009g00080000000,"1654 smallman st, pittsburgh, pa 15222",keicher bros enterprises,p.j. dick incorporated,interior and exterior renovation of existing s...,9739000.0,2019,march,3
1,2019-03-01,18-b-03957,2.0,0009g00080000000,"1606 smallman st, pittsburgh, pa 15222",keicher bros enterprises,p.j. dick incorporated,new construction of accessory parking structur...,3648000.0,2019,march,3

## Combine the sets from API, xls, and brute force xlsx files

In [12]:
api = pd.read_csv('api_data_clean.csv')
excl = pd.read_csv('failed_api_data.csv')
xls = pd.read_csv('failed_records_data.csv')

C:\Users\danie\anaconda_3\lib\site-packages\IPython\core\interactiveshell.py:3155: DtypeWarning: Columns (0,2,9) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [22]:
api.dtypes

structure_type       object
parcel               object
neighborhood         object
owner                object
issued               object
work description     object
permit               object
contractor           object
address              object
work_type            object
ward                 object
id                  float64
cost                 object
year                  int64
month                object
source               object
dtype: object

In [23]:
excl.dtypes

permit               object
ward                float64
parcel               object
address              object
owner                object
contractor           object
work description     object
cost                float64
issued               object
year                  int64
month                object
source               object
dtype: object

In [24]:
excl['ward'] = excl['ward'].astype('O')

In [25]:
excl['cost'] = excl['cost'].astype('O')

In [26]:
xls.dtypes

issued               object
permit               object
ward                float64
parcel               object
address              object
owner                object
contractor           object
work description     object
cost                float64
year                  int64
month                object
mn                    int64
source               object
dtype: object

In [27]:
xls['cost'] = xls['cost'].astype('O')
xls['ward'] = xls['ward'].astype('O')

In [28]:
df.dtypes

issued              datetime64[ns]
permit                      object
ward                       float64
parcel                      object
address                     object
owner                       object
contractor                  object
work description            object
cost                       float64
year                         int64
month                       object
mn                           int64
dtype: object

In [29]:
df['cost'] = df['cost'].astype('O')
df['ward'] = df['ward'].astype('O')
df['issued']=df['issued'].astype('O')

In [30]:
all_data = pd.concat([api,excl,xls,df], axis=0)

In [31]:
all_data.head()

,structure_type,parcel,neighborhood,owner,issued,work description,permit,contractor,address,work_type,ward,id,cost,year,month,source,mn
0,residential - single family,0049-p-00248-0000-00,lower lawrenceville,1301grandview i llc,2021-01-01t00:00:00,"interior alterations, new exterior doors and w...",ep-2020-20992,d & s electric pgh llc,"335 39th st, pittsburgh, 15201",addition / alteration,6,1.0,3000.0,2021,january,API,NaN
1,residential - two-family,0026-e-00072-0000-00,polish hill,wylie holdings lp,2021-01-04t00:00:00,replacement of existing two-story deck structu...,bp-2020-17699,w king properties inc dba w king builders,"3208 dobson st, pittsburgh, 15219",addition / alteration,6,2.0,12000.0,2021,january,API,NaN
2,residential - single family,0059-j-00282-0000-00,carrick,marcella paula hilary rhae,2021-01-04t00:00:00,"10'x12"" deck",bp-2020-17732,stone leigh construction and remodeling,"313 e agnew ave, pittsburgh, 15210",addition / alteration,29,3.0,8565.0,2021,january,API,NaN
3,residential - single family,0085-k-00033-0000-00,squirrel hill north,jain girish,2021-01-04t00:00:00,"construct 2 story addition with basement, 1st ...",19-b-01691,"senko construction, inc","1200 s negley ave, pittsburgh, 15217",addition / alteration,14,4.0,150000.0,2021,january,API,NaN
4,residential - single family,0085-k-00033-0000-00,squirrel hill north,jain girish,2021-01-04t00:00:00,new partially covered 1st floor deck with jacu...,bp-2020-05162,"senko construction, inc","1200 s negley ave, pittsburgh, 15217",addition / alteration,14,5.0,1.0,2021,january,API,NaN

In [32]:
len(all_data)

75065

In [33]:
mn_d = {'january':1, 'february':2,'march':3, 'april':4,
       'may':5, 'june':6,'july':7, 'august':5,
       'september':9, 'october':10,'november':11, 'december':12}

In [34]:
all_data['mn'] = all_data['month'].apply(lambda x: mn_d[x])

In [35]:
deduped = all_data.drop_duplicates(subset=['parcel','permit','address', 'cost'], keep='first')

In [36]:
# After dro
len(deduped)

71210

In [37]:
all_data[~all_data.index.isin(deduped.index)]

,structure_type,parcel,neighborhood,owner,issued,work description,permit,contractor,address,work_type,ward,id,cost,year,month,source,mn
3054,commercial - all other uses,0001-g-00239-0000-00,central business district,g&i viii mjw 11 stanwix llc,2020-10-29t00:00:00,"use of partial 10th floor for ""neyers office f...",fas-2020-16115,apex electrical solutions inc,"11 stanwix st, pittsburgh, 15222",addition / alteration,1,825.0,2400.0,2020,october,API,10
3903,residential - single family,0126-n-00166-0000-00,squirrel hill north,hagan susan m,2020-09-25t00:00:00,"construct deck with stairs on 1st floor rear, ...",bp-2020-11684,"ngs construction, llc","6676 woodwell st, pittsburgh, 15217",addition / alteration,14,793.0,40000.0,2020,september,API,9
4454,commercial - all other uses,0008-k-00022-0000-00,north shore,north shore xiv llc,2020-08-17t00:00:00,interior alterations for tenant fit out on sec...,bp-2020-05500,"continental building company ii, llc","275 north shore dr, pittsburgh, 15212",NaN,22,397.0,470000.0,2020,august,API,5
5247,commercial - all other uses,0051-l-00262-0000-00,bloomfield,legacy affiliated ventures lp,2020-07-10t00:00:00,sola salon(6488 sf) studios in a 1 story struc...,bp-2020-06557,banyan construction services,"5259 liberty ave, pittsburgh, 15224",NaN,8,268.0,589245.0,2020,july,API,7
8129,residential - single family,0024-e-00189-0000-00,east allegheny,kiwew holdings llc,2020-03-11t00:00:00,new 2nd story rear deck ; new rear dormer at roof,bp-2019-10382,steelmark construction llc,"841 vista st, pittsburgh, 15212",NaN,23,144.0,12000.0,2020,march,API,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14956,NaN,0128n00011000000,NaN,feldstein norman r,6/5/2017,rebuild 2 story single family dwelling with 9'...,17-b-00965,exceptional exteriors and renovations,"1001 hasley ln, pittsburgh, pa 15217",NaN,14,NaN,120000,2017,june,xslx,6
15254,NaN,0128a00056000001,NaN,board of public education of the school distri...,6/12/2017,"exterior exhaust fans, interior ductwork, pipi...",17-m-00140,NaN,"2332 beechwood blvd, pittsburgh, pa 15217",NaN,14,NaN,160000,2017,june,xslx,6
15336,NaN,0049g00222000000,NaN,children's hospital of pittsburgh of theupmc h...,6/13/2017,hvac related to 17-b-01099,17-m-00473,NaN,"4401 penn ave, pittsburgh, pa 15224",NaN,9,NaN,5000,2017,june,xslx,6
15448,NaN,0080h00035000000,NaN,urban capital group llc,6/15/2017,occupancy only,17-occ-00468,NaN,"5126 keystone st, pittsburgh, pa 15201",NaN,10,NaN,0,2017,june,xslx,6
16020,NaN,0050n00232000000,NaN,aul george l,6/30/2017,railings posts and roof same size same locatio...,17-b-02839,roobee,"244 s mathilda st, pittsburgh, pa 15224",NaN,8,NaN,6200,2017,june,xslx,6

In [38]:
# IT looks like permits that are duplicated are just turned over month on month
# So, we can sort and keep first for when the work began. If they share the 
# same permit number, address and cost, it is very clearly just a continuing project
all_data[all_data['permit']=='bp-2020-11684']

,structure_type,parcel,neighborhood,owner,issued,work description,permit,contractor,address,work_type,ward,id,cost,year,month,source,mn
2355,residential - single family,0126-n-00166-0000-00,squirrel hill north,hagan susan m,2020-10-06t00:00:00,"construct deck with stairs on 1st floor rear, ...",bp-2020-11684,"ngs construction, llc","6676 woodwell st, pittsburgh, 15217",addition / alteration,14,124.0,40000.0,2020,october,API,10
3903,residential - single family,0126-n-00166-0000-00,squirrel hill north,hagan susan m,2020-09-25t00:00:00,"construct deck with stairs on 1st floor rear, ...",bp-2020-11684,"ngs construction, llc","6676 woodwell st, pittsburgh, 15217",addition / alteration,14,793.0,40000.0,2020,september,API,9

In [39]:
all_data = all_data.sort_values(['year','mn'])

In [40]:
all_data.drop_duplicates(subset=['parcel','permit','address', 'cost'], keep='first', inplace=True)

In [41]:
all_data.to_csv('all_permit_v1.csv', index=False)